name: Feature Workflow

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - feature/**

jobs:
  build:
    name: Feature Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: portfolio/
          key: ${{ runner.os }}-dependencies

      - name: Install dependencies
        run: npm install
          npm run lint
          npm run build --if-present
          npm run test --if-present
      
      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present
      
      - name: Test
        run: |
          echo "Add some tests for intergration suite testing"
          npm run test --if-present
