name: Deploy

on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: sebastian-kloogh-portfolio
          path: ./dist/*
          if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sebastian-kloogh-portfolio
          path: ./dist/*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: public
