name: Production Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: portfolio/
          key: ${{ runner.os }}-dependencies

      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: portfolio
          path: ./dist/*
          if-no-files-found: error

  deploy:
    name: Production Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: portfolio
          path: ./dist/*